### ISSUE TITLE
On assigning the documentation.

### ISSUE THREAD

**Issue by fonsecadh** [Arquisoft/dechat_en1a#2]
We have to assign the documentation for at least the first three chapters, concerning the **problem of the task**.

**Comment by uo251119** [comment]
I suggest assigning it the same way we did it for the first document. In this case I think is best to assign 2 people to the second one and four for the third one, as it has two sections.
Example:
2 - Hugo
2 - Varis
3.1- Teji
3.1 - Jaime
3.2 - Paco
3.2 - Ivan

**Comment by pacojq** [comment]
It will be better if we close this issue and create one issue per file in the documentation.
